version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: obrio_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: obrio
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: obrio_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  backend:
    build: .
    container_name: backend
    depends_on:
      - postgres
      - redis
    command: bash -c "npx prisma migrate deploy && npm start"
    environment:
      - DATABASE_URL=postgresql://root:root@postgres:5432/obrio?schema=public
      - REDIS_HOST=redis
    env_file:
      - .env
    ports:
      - '3000:3000'
    restart: always

volumes:
  postgres_data:
  redis_data:
